# Generated by Django 5.0.4 on 2024-05-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0003_generofilme"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlataformaStreaming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
    ]
