# Generated by Django 5.0.4 on 2024-05-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0008_alter_minhaplaylist_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
