# Generated by Django 5.0.4 on 2024-05-14 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0009_playlist_delete_usuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MinhaPlaylist",
        ),
    ]
