# Generated by Django 5.0.4 on 2024-05-14 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0011_playlistuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaylistFilme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="list.filmes"
                    ),
                ),
                (
                    "play",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="list.playlistuser",
                    ),
                ),
            ],
        ),
    ]
