# Generated by Django 5.0.4 on 2024-06-04 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0016_alter_skin_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comentario", models.CharField(max_length=255)),
                ("nota", models.IntegerField()),
            ],
        ),
    ]
