# Generated by Django 5.0.4 on 2024-06-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0017_avaliacao"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skinuser",
            name="skin",
        ),
        migrations.AddField(
            model_name="skinuser",
            name="img",
            field=models.ImageField(default="", upload_to="static/"),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Skin",
        ),
    ]
