# Generated by Django 5.0.4 on 2024-06-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("list", "0018_remove_skinuser_skin_skinuser_img_delete_skin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skinuser",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="static/"),
        ),
    ]
