# Generated by Django 5.0.4 on 2024-06-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0020_alter_skinuser_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
