# Generated by Django 5.0.4 on 2024-06-08 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0022_alter_filmes_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.filmes'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
