# Generated by Django 5.0.4 on 2024-06-09 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0023_avaliacao_filme_avaliacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='skin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.skinuser'),
        ),
    ]
