# Generated by Django 5.0.4 on 2024-06-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0024_avaliacao_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinuser',
            name='img',
            field=models.ImageField(blank=True, default='/media/images/profile-default.png', null=True, upload_to='images/'),
        ),
    ]
