# Generated by Django 5.0.4 on 2024-06-13 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0025_alter_skinuser_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='user',
        ),
        migrations.AlterField(
            model_name='skinuser',
            name='img',
            field=models.ImageField(blank=True, default='/images/profile-default.png', null=True, upload_to='images/'),
        ),
    ]
