# Generated by Django 5.0.4 on 2024-06-13 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0026_remove_avaliacao_user_alter_skinuser_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='skin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.skinuser'),
        ),
    ]
