# Generated by Django 5.0.4 on 2024-06-13 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0027_alter_avaliacao_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='skin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.skinuser'),
        ),
    ]
