# Generated by Django 5.0.4 on 2024-06-13 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0028_alter_avaliacao_skin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmes',
            name='cover',
            field=models.ImageField(blank=True, default='/images/filme-default.png', null=True, upload_to='images/'),
        ),
    ]
