# Generated by Django 5.0.4 on 2024-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0029_alter_filmes_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('likeCount', models.IntegerField()),
                ('deslikeCount', models.IntegerField()),
            ],
        ),
    ]
