# Generated by Django 5.0.4 on 2024-06-14 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0030_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.like'),
        ),
    ]
