# Generated by Django 5.0.4 on 2024-06-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0034_avaliacao_deslikecount_avaliacao_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
