# Generated by Django 5.0.4 on 2024-07-27 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0037_remove_avaliacao_deslikecount_remove_avaliacao_like_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='list.avaliacao')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.filmes')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.generofilme')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.plataformastreamingfilme')),
            ],
        ),
    ]
