# Generated by Django 5.0.4 on 2024-07-27 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0039_avaliacao_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='plataforma',
        ),
        migrations.CreateModel(
            name='FilmeAgregador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agregador', to='list.filmes')),
                ('generos', models.ManyToManyField(related_name='agregador', to='list.genero')),
                ('plataformas', models.ManyToManyField(related_name='agregador', to='list.plataformastreaming')),
            ],
        ),
    ]
