# Generated by Django 5.0.4 on 2024-07-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0040_remove_postagem_genero_remove_postagem_plataforma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.filmeagregador'),
        ),
    ]
