# Generated by Django 5.0.4 on 2024-07-27 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0041_alter_postagem_filme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postagem',
            name='avaliacao',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='postagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='list.postagem'),
        ),
    ]
