# Generated by Django 5.0.4 on 2024-08-02 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0042_remove_postagem_avaliacao_avaliacao_postagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postagem',
            name='filme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agregador', to='list.filmes'),
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='filme',
        ),
        migrations.AddField(
            model_name='postagem',
            name='generos',
            field=models.ManyToManyField(related_name='agregador', to='list.genero'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='plataformas',
            field=models.ManyToManyField(related_name='agregador', to='list.plataformastreaming'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='list.postagem'),
        ),
        migrations.DeleteModel(
            name='FilmeAgregador',
        ),
    ]
