# Generated by Django 5.0.4 on 2024-08-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0043_alter_postagem_filme_remove_avaliacao_filme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='postagem',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='filme',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='list.filmes'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Postagem',
        ),
    ]
