# Generated by Django 5.0.4 on 2024-08-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0045_plataformastreaming_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmes',
            name='sinopse',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis ligula sed tortor cursus scelerisque vitae nec lacus. Nunc semper rhoncus ipsum quis egestas. Pellentesque sed porttitor est. Maecenas sodales felis non tristique tincidunt.', max_length=255),
            preserve_default=False,
        ),
    ]
