# Generated by Django 5.0.4 on 2024-08-03 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0046_filmes_sinopse'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('filme', 'skin')},
        ),
    ]
